videolandia/Models/Filme.cs
using System.ComponentModel.DataAnnotations;
using videolandia.Models;

namespace videolandia.Models
{
    public class Filme
    {
        public int Id { get; set; }

        [Display(Name = "Nome do Filme")]
        [Required]
        public string NomeFilme { get; set; }

        [Display(Name = "Pôster")]
        [Required]
        [DataType(DataType.Url)]
        public string PosterUrl { get; set; }

        [Display(Name = "Data de Lançamento")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime DtLancamento { get; set; }

        [Display(Name = "Diretor")]
        public string Diretor { get; set; }

        public List<ArtistaFilme> Artistas { get; } = new List<ArtistaFilme>();
        public List<GeneroFilme> Generos { get; } = new List<GeneroFilme>();
    }
}

videolandia/Controllers/ArtistasController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using videolandia.Data;
using videolandia.Models;

namespace videolandia.Controllers
{
    public class ArtistasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArtistasController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Artista == null)
            {
                return Problem("A entidade 'MvcMovieContext.Movie' é nula.");
            }

            var artistas = from a in _context.Artista
                           select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                artistas = artistas.Where(s => s.NomeArtista!.ToUpper().Contains(searchString.ToUpper()));
            }

            return View(await artistas.ToListAsync());
        }

        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artista = await _context.Artista
                .Include(x => x.Filmes)
                .ThenInclude(x => x.Filme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artista == null)
            {
                return NotFound();
            }

            return View(artista);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Criar([Bind("Id,NomeArtista,DtNascimento,PaisNascimento,ArtistaUrl")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artista);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(artista);
        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artista = await _context.Artista.FindAsync(id);
            if (artista == null)
            {
                return NotFound();
            }
            return View(artista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, [Bind("Id,NomeArtista,DtNascimento,PaisNascimento,ArtistaUrl")] Artista artista)
        {
            if (id != artista.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artista);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistaExiste(artista.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(artista);
        }

        public async Task<IActionResult> Deletar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artista = await _context.Artista
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artista == null)
            {
                return NotFound();
            }

            return View(artista);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletarConfirmado(int id)
        {
            var artista = await _context.Artista.FindAsync(id);
            if (artista != null)
            {
                _context.Artista.Remove(artista);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistaExiste(int id)
        {
            return _context.Artista.Any(e => e.Id == id);
        }
    }
}

videolandia/Controllers/FilmesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using videolandia.Data;
using videolandia.Models;

namespace videolandia.Controllers
{
    public class FilmesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilmesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Filme == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }

            var movies = from m in _context.Filme
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.NomeFilme!.ToUpper().Contains(searchString.ToUpper()));
            }

            return View(await movies.ToListAsync());
        }

        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .Include(x => x.Artistas)
                .ThenInclude(x => x.Artista)
                .FirstOrDefaultAsync(m => m.Id == id);

            var genero = await _context.Filme
                .Include(x => x.Generos)
                .ThenInclude(x => x.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Criar([Bind("Id,NomeFilme,PosterUrl,DtLancamento,Diretor")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }
            return View(filme);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, [Bind("Id,NomeFilme,PosterUrl,DtLancamento,Diretor")] Filme filme)
        {
            if (id != filme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        public async Task<IActionResult> Deletar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletarConfirmado(int id)
        {
            var filme = await _context.Filme.FindAsync(id);
            if (filme != null)
            {
                _context.Filme.Remove(filme);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id)
        {
            return _context.Filme.Any(e => e.Id == id);
        }
    }
}

videolandia/Views/Filmes/Criar.cshtml
@model videolandia.Models.Filme

@{
    ViewData["Title"] = "Criar Filme";
}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<h1>Criar Filme</h1>

<h4>Detalhes do Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Nome do Filme -->
            <div class="form-group">
                <label asp-for="NomeFilme" class="control-label"></label>
                <input asp-for="NomeFilme" class="form-control" />
                <span asp-validation-for="NomeFilme" class="text-danger"></span>
            </div>

            <!-- URL do Poster -->
            <div class="form-group">
                <label asp-for="PosterUrl" class="control-label"></label>
                <input asp-for="PosterUrl" class="form-control" />
                <span asp-validation-for="PosterUrl" class="text-danger"></span>
            </div>

            <!-- Data de Lançamento -->
            <div class="form-group">
                <label asp-for="DtLancamento" class="control-label"></label>
                <input asp-for="DtLancamento" class="form-control" type="date" />
                <span asp-validation-for="DtLancamento" class="text-danger"></span>
            </div>

            <!-- Diretor -->
            <div class="form-group">
                <label asp-for="Diretor" class="control-label"></label>
                <input asp-for="Diretor" class="form-control" />
                <span asp-validation-for="Diretor" class="text-danger"></span>
            </div>
            <br/>
            <!-- Botões de Submissão e Voltar -->
            <div class="form-group">
                <input type="submit" value="Criar Novo" class="btn btn-primary" style="width: 200px" />
            </div>
            <br />
        </form>
    </div>
</div>
<form asp-action="Index" method="get" class="d-inline">
    <button type="submit" class="btn btn-dark" style="width: 200px">Voltar à Lista</button>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

videolandia/Views/Filmes/Deletar.cshtml
@model videolandia.Models.Filme

@{
    ViewData["Title"] = "Excluir Filme";
}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<h1>Excluir Filme</h1>

<h3>Você tem certeza de que deseja excluir este filme?</h3><br/>
<div>
    <h4>Detalhes do Filme</h4>
    <hr />
    <dl class="row">
        <!-- Nome do Filme -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeFilme)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeFilme)
        </dd>

        <!-- URL do Poster -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PosterUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PosterUrl)
        </dd>

        <!-- Data de Lançamento -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DtLancamento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DtLancamento)
        </dd>

        <!-- Diretor -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Diretor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Diretor)
        </dd>
    </dl>

    <!-- Formulário de exclusão -->
    <form asp-action="Deletar">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" style="width: 200px;" /> 
        <a asp-action="Index" class="btn btn-dark" style="width: 200px;">Voltar para a Lista</a>
    </form>
</div>

videolandia/Views/Filmes/Detalhes.cshtml
@model videolandia.Models.Filme

@{
    ViewData["Title"] = "Detalhes do Filme";
}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<h1>Detalhes</h1>

<div>
    <!-- Nome do Filme -->
    <h4>
        <p style="margin-top: 10px; font-weight: bold;">@Model.NomeFilme</p>
    </h4>
    <hr />

    <dl class="row">
        <div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: flex-start;">

            <!-- Imagem do Poster -->
            <dd class="col-sm-10">
                <img src="@Model.PosterUrl" height="150"
                     style="display: block; float: left; margin: 0 auto; border-radius: 10px; box-shadow: 3px 3px 5px rgba(0, 0, 0, 0.3);"
                     alt="@Model.NomeFilme" />
            </dd>

            <!-- Data de Lançamento -->
            <dt class="col-sm-2">
                Data de Lançamento
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DtLancamento)
            </dd>

            <!-- Diretor -->
            <dt class="col-sm-2">
                Diretor
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Diretor)
            </dd>

            <!-- Gêneros -->
            <dd class="col-sm-10">
                <p style="font-weight: bold;">Gênero(s)</p>
                @foreach (var item in Model?.Generos)
                {
                    @item.Genero?.NomeGenero

                    <br />
                }
            </dd>
        </div>
    </dl>

    <!-- Artistas -->
    <div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: center;">
        @foreach (var item in Model?.Artistas)
        {
            <!-- Link para detalhes do artista -->
            <div style="text-align: center; width: 150px;">
                <a asp-area="" asp-controller="Artistas" asp-action="Detalhes" asp-route-id="@item.Artista.Id">
                    <img src="@item.Artista.ArtistaUrl" height="100"
                         style="display: block; margin: 0 auto; border-radius: 10px; box-shadow: 3px 3px 5px rgba(0, 0, 0, 0.3);"
                         alt="@item.Artista?.NomeArtista" />
                </a>
                <p style="margin-top: 10px; font-weight: bold;">@item.Artista?.NomeArtista</p>
                <p>@item.Personagem</p>
            </div>
        }
    </div>
</div>

<!-- Links para edição e lista -->
@if (User.Identity.IsAuthenticated)
{
    <div class="d-flex flex-row gap-2 mt-4">
        <a asp-action="Editar" asp-route-id="@Model?.Id" class="btn btn-primary" style="width: 200px;">Editar</a>
        <a asp-action="Index" class="btn btn-dark" style="width: 200px;">Voltar para a lista</a>
    </div>
}
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br />

videolandia/Views/Filmes/Editar.cshtml
@model videolandia.Models.Filme

@{
    ViewData["Title"] = "Editar Filme";
}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<h1>Editar</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Campo Hidden para Id -->
            <input type="hidden" asp-for="Id" />

            <!-- Campo Nome do Filme -->
            <div class="form-group">
                <label asp-for="NomeFilme" class="control-label">Nome do Filme</label>
                <input asp-for="NomeFilme" class="form-control" />
                <span asp-validation-for="NomeFilme" class="text-danger"></span>
            </div>

            <!-- Campo URL do Poster -->
            <div class="form-group">
                <label asp-for="PosterUrl" class="control-label">URL do Poster</label>
                <input asp-for="PosterUrl" class="form-control" />
                <span asp-validation-for="PosterUrl" class="text-danger"></span>
            </div>

            <!-- Campo Data de Lançamento -->
            <div class="form-group">
                <label asp-for="DtLancamento" class="control-label">Data de Lançamento</label>
                <input asp-for="DtLancamento" class="form-control" />
                <span asp-validation-for="DtLancamento" class="text-danger"></span>
            </div>

            <!-- Campo Diretor -->
            <div class="form-group">
                <label asp-for="Diretor" class="control-label">Diretor</label>
                <input asp-for="Diretor" class="form-control" />
                <span asp-validation-for="Diretor" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" style="width: 200px;" />
            </div>

        </form>
    </div>
</div>

<!-- Link para voltar à lista -->
<div class="d-flex flex-column align-items-start gap-2 mt-4">
    <a asp-action="Index" class="btn btn-dark" style="width: 200px;">Voltar para a Lista</a>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

videolandia/Views/Filmes/Index.cshtml
@model IEnumerable<videolandia.Models.Filme>

@{
    ViewData["Title"] = "Índice de Filmes";
}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<h1>Índice de Filmes</h1>

<p>
    <form asp-action="Criar">
        <button type="submit" class="btn btn-dark" style="width: 300px">Criar Novo</button>
    </form>
</p>
<br/>
<form asp-controller="Filmes" asp-action="Index" method="get">
    <p>
        <label>Título: <input type="text" name="SearchString" /></label>
        <input type="submit" value="Filtrar" />
    </p>
</form>
<br/>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="@item.PosterUrl" class="card-img-top" alt="Capa de @item.NomeFilme">
                <div class="card-body">
                    <h5 class="card-title">@item.NomeFilme</h5>
                    <p class="card-text">Lançamento: @item.DtLancamento.Year</p>
                    <p class="card-text">Diretor: @item.Diretor</p>

                    <!-- Ações -->
                    <div>
                        <a class="btn btn-primary btn-sm w-100 mb-2" asp-action="Editar" asp-route-id="@item.Id">Editar</a>
                        <a class="btn btn-info btn-sm w-100 mb-2" asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a>
                        <a class="btn btn-danger btn-sm w-100" asp-action="Deletar" asp-route-id="@item.Id">Excluir</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>